//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Critters.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roster
    {
        public string playerid { get; set; }
        public Nullable<int> jersey { get; set; }
        public string fname { get; set; }
        public string sname { get; set; }
        public string position { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public Nullable<int> height { get; set; }
        public Nullable<int> weight { get; set; }
        public string birthcity { get; set; }
        public string birthstate { get; set; }
    }
}
